version: "3.7"

services:
  api:
    container_name: "api"
    image: docke-node-mongo
    ports:
      - "1997:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
  db:
    container_name: "db"
    image: mongo
    ports:
      - "27017:27017"